### ISSUE TITLE
For ASDA, suggest to support click+collect

### ISSUE THREAD

**Issue by glucee** [malhotra-sidharth/delivery-slot-notify#1]
Right now if the page switches to click+collect tab in ASDA, the addon keeps notifying the users about the available slot. I suggest to also recognise the keyword 'Free' for click+collect.

**Comment by malhotra-sidharth** [comment]
@glucee Thanks for the feedback. Working on it. Will notify you once the release is published on the chrome store.

**Comment by malhotra-sidharth** [comment]
@glucee Added support for click+collect. Published to chrome store. Should be updated in some time. Thanks. :)
